name: project312_2
description: "bunqbunq 2.0"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  cloud_functions: ^5.3.4
  go_router: ^14.8.1
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0
  firebase_storage: ^12.4.4
  image_picker_web: ^4.0.0
  country_pickers: ^3.0.1
  clipboard: ^0.1.3
  google_fonts: ^6.2.1
  uuid: ^4.5.1
  image_picker: ^1.0.0
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bunqbunq.png